etlegacy_user: etlegacy
etlegacy_group: etlegacy

etlegacy_install_dir: /opt/etlegacy

wolfet_installer_url: "https://cdn.splashdamage.com/downloads/games/wet/et260b.x86_full.zip"
wolfet_tmp_dir: "/tmp/wolfet_extract"

etlegacy_dirs:
  - etmain
  - home
  - home/legacy
  - legacy


etlegacy_download_url: "https://www.etlegacy.com/download/file/700"

etlegacy_hostname: "ET:Legacy Server"
etlegacy_password: "<CHANGE_ME>"
etlegacy_rcon_password: "<CHANGE_ME>"
etlegacy_www_baseurl: ""

etlegacy_map: battery
etlegacy_gametype: 6

etlegacy_motd: "Welcome to Hell"
etlegacy_maxclients: 20

etlegacy_advert: "1"
etlegacy_flood_protect: "1"
etlegacy_voice_chats_allowed: "5"
etlegacy_min_map_age: "1"