---
- name: Copy custom maps to legacy directory
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ etlegacy_install_dir }}/legacy/{{ item }}"
    owner: "{{ etlegacy_user }}"
    group: "{{ etlegacy_group }}"
    mode: "0644"
  loop: "{{ etlegacy_custom_maps }}"
  notify: restart etlegacy
